services:
  backend:
    env_file:
      - .env
    tty: true
    image: alfaid-web-backend
    build:
      context: ./
      dockerfile: ./dockerfile
    volumes:
      - ./:/home/node/app/
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'frotas'
    logging:
      driver: none
    ports:
      - 5432:5432
