version: '3.4'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'frotas'
    logging:
      driver: none
    ports:
      - 5432:5432
