services:
  backend:
    env_file:
      - .env
    tty: true
    image: alfaid-web-backend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    volumes:
      - ./:/home/node/app/
      - node_modules:/home/node/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - database

  database:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'frotas'
    logging:
      driver: none
    ports:
      - 5432:5432

volumes:
  node_modules:
